apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: {{ .Release.Namespace | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project | quote }}
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 8.5.10
    helm:
      releaseName: nextcloud
      valuesObject:
        ingress:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/hostname: {{ printf "cloud.%s" .Values.domain | quote }}
      nextcloud:
        host: {{ printf "cloud.%s" .Values.domain | quote }}
        existingSecret:
          enabled: true
      redis:
        enabled: true
        auth:
          enabled: false
      service:
        annotations:
          traefik.ingress.kubernetes.io/service.sticky.cookie: "true"

  destination: {{ .Values.spec.destination | toYaml | nindent 4 }}
  syncPolicy: {{ .Values.spec.syncPolicy | toYaml | nindent 4 }}
