---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
spec:
  encryptedData:
    apiKey: AgBxn41PE1epy5TxYhoYq/EzP0VUAD8WLZnmoaWlmEAxMYA5ODwcGt0iIVoRmrH4bqqOxws6gl1r3uJjmiNtjf0DZUz2exgg7gONE2u/6NDntgk/EP7HxLVeHuVNI3jF7PmBsK32evNyChuk21963FyKu2VDfqY895D1TlNfJUfFsB2iHQAEn/W0iW7za0//5rfaZeM5gh8Yt8+DJ47hH+L6xZBgpLIFAxjpXLTu5w4L8FhpxR595VGU6vnotLUOw23dLJRM+zx/ToLo0kLjjtAv7E1XFbv+xoxqcJWcSMeWj8C7uq+8lXIJTMxUWaBS2+TW4MJ8/geoVbLYcKG8ySBURX1WGqfBUBwTke+C7q0fCA9cAy5rPr3tmZAl2cg/1yR6fjgSGRBl6eLp6yfUUJFRuv0dyJGuEhm4Y/8dlLLSmx+LfkHLA95KoIQZ7vBRLvJEZ7THk/HyheNWLRhwF0DXeMaLMsuh60WDhFydCGWARmdV0SELZAiMQ59jLKQ8t95WrjX+6t2OOmi/Y47ynGq5Aao22XVVZqvGEOq09mqfDad/ov5sbjUgJZFyVHxBM7fTRZLJv5umcTydEzapxtgoK+oO1CVPBMEQTUj2+5GaXM21iVCDI/nAe/POu8TIaozzeZSl35gISCCwfsOeJ1J7G3gFBUraMqumJiv1QCIX3UN6P6sbAyt6D1qYaxFPGOtYwBHSHpIPDabN8KIgEnwl1DZgbyYNz5lF0Mk4vRQYFnywk45n60dh
  template:
    metadata:
      name: cloudflare-api-key
