---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgCPKZCGVvJypFBQ08X1GtE+bOFnGRNJ2KbkoiMLRTCdLC+ZrE5+tR+ovClYAH8aPbZfLXutnDM6HJvh2U3ydEbTJvhB62bipyGt9AKTVN4ESr74C6Z/TM/wRcjLtntqSVT7f5njjL2U5+wWvb0mMY/wMWis7rYOzF6Ejwq4NiDPXb0Y/958iix+/pRF2yyypbT9iSBvCh7X7xb6V7oK5d7F8ZJ/Rlt5vE2k4Ep6od4GyWX2c5ANwv1Y9zDnxQzgMzqhIGWu4XK40EcNvArhf6Osn7hJKKM/6/EfMlB7ImSKTmi0OYq8dyDmusiG7GlB3iHiEN9DSYNJl/zDV/ZhcgepZYnNLx6SKNt8QnQ9eIG5oNPzJTWD1KMoYbRHlHbWJJnVjL1Iq6GEpYkXXnG1eibW/j6+n+0Zb4r6QDBMAb7RQg57VokLDrsl0Zkf3JX+iDiPo0bgcm7+CxIBpjnvr2bSEFHJ/2q3tgh/+SYvVVxEQJppcwlp4gw1pjKS9+cR5p6ejqzQS7wKO3U/einfkZ8DSYu+qG+5pO9jNt4nCkn9OHsxJGAQhZ/I1zqNhZ4BpqmPNBbYDuLCVvSaJ/LP5QoKvwT1YWNOyQMdTPFj0Fx7VROjoImWCCV0TpUPpuvw+/1tEt7x/t7sEdZcf3UPcGmpQsvNjH6yoW0eMZQ8zLi0RwQ0ksQAKbvhy0KJ3RuedyYURpNZw6ebh/2gqW3y15hX4XKQCiWimenDKNkpYd5jOjtZb9ucGM9g
  template:
    metadata:
      name: cloudflare-api-key
      namespace: external-dns
